hooks:
  update_modules:
    pre:
      - echo "before update-modules"
    post:
      - echo "after update-modules"
  release:
    pre:
      - npm run build:dist
    post:
      - echo "after release"
  gh_pages:
    pre:
      - echo "before gh-pages"
    post:
      - echo "after gh-pages"
config:
  git_user_name: mere
  git_user_email: github@zoltanb.co.uk
  npm_update_depth: 0
  version_prefix: v
  create_branch: true
  npm_shrinkwrap: true
  create_gh_pages: true
  gh_pages_dir: null
circle: {}
